version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: manishafashion
    ports:
      - "5432:5432"

  app:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:123456789@db:5432/manishafashion
    ports:
      - "80:80"
    depends_on:
      - db
